const ACCESS_TOKEN = "ASDASDASVSSADFS2734723H"
const REFRESH_TOKEN = "bzbxcbzxbczbxcb"
const TOKEN_TIME_LIFE = '30s'

module.exports = {
    ACCESS_TOKEN: ACCESS_TOKEN,
    REFRESH_TOKEN: REFRESH_TOKEN,
    TOKEN_TIME_LIFE: TOKEN_TIME_LIFE
}